# Generated by Django 4.2.7 on 2023-11-14 15:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='email',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testmodel',
            name='password',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testmodel',
            name='pole',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
