# Generated by Django 4.2.7 on 2023-11-14 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wer', '0002_testmodel_email_testmodel_password_testmodel_pole'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testmodel',
            name='pole',
        ),
        migrations.RemoveField(
            model_name='testmodel',
            name='title',
        ),
    ]
